# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Sops Binary Installer
        uses: mdgreenwald/mozilla-sops-action@v1.2.0
        id: install
      - name: Import example PGP key
        run: |
          gpg --import tests/sops_functional_tests_key.asc
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 sops_git_hooks
      - name: Install package
        run: |
          pip install .
      - name: Lint tests flake8
        run: |
          flake8 tests
      - name: Test with pytest
        run: |
          pytest tests
